name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Run tests
        run: mvn test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}